139 save telemetry data to file
ciselab/TestGenie pull request #143
Opened 2022-06-01 17:55 UTC by jzelenjak

# Description of changes made
- Telemetry data is now saved into a *json* file in a user-specified folder
- Every time the upload method in the telemetry service is called, a new file in that directory is created using the current timestamp as the filename, and all currently scheduled tests are saved to that file. If there is no currently scheduled tests, no file is created
- `submitTelemetry` method is now called every 5 minutes and when intellij exits

# Why is merge request needed
This merge request is needed since it is part of a feature requested by the client

# Other notes
Closes #139 

# What is missing?

- [x] I have checked that I am merging into correct branch

2022-06-01 19:17 UTC, martinmladenov requested changes

2022-06-01 19:17 UTC, martinmladenov commented on src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestGenieTelemetryService.kt
> +        val separator: String = if (System.getProperty("os.name").contains("Windows")) "\\" else "/"
Consider using `File.separator`

2022-06-01 19:17 UTC, martinmladenov commented on src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestGenieTelemetryService.kt
> +            ?: System.getProperty("user.dir")
Maybe the default path should be something like `<user.dir>/TestGenieTelemetry` instead of just dumping files in the home directory?

2022-06-01 19:17 UTC, martinmladenov commented on src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestGenieTelemetryService.kt
> +        val telemetryFileName: String = dirName.plus(Timestamp(System.currentTimeMillis()).toString())
The file name should end with `.json`

2022-06-01 19:17 UTC, martinmladenov commented on src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginComponent.kt
> +        telemetryPathTextField.toolTipText = "Choose a file to save the changes into"
```suggestion
        telemetryPathTextField.toolTipText = "Choose a directory to save telemetry data into"
```

2022-06-02 10:52 UTC, jzelenjak commented on src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestGenieTelemetryService.kt
> +        val separator: String = if (System.getProperty("os.name").contains("Windows")) "\\" else "/"
Has been changed

2022-06-02 10:53 UTC, jzelenjak commented on src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginComponent.kt
> +        telemetryPathTextField.toolTipText = "Choose a file to save the changes into"
Has been changed

2022-06-02 12:36 UTC, martinmladenov commented on src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestGenieTelemetryService.kt
> +            ?: System.getProperty("user.dir")
Sure, just leave it as is then.

2022-06-02 12:58 UTC, jzelenjak commented on src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/listener/TestGenieTelemetrySubmitListenerImpl.kt
> +            10000, 10000
For now - yes, since it is easier to debug. It will be changed back when everything is fixed

2022-06-02 13:07 UTC, jzelenjak commented on src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/listener/TestGenieTelemetrySubmitListenerImpl.kt
> +    override fun projectOpened(project: Project) {
The listener is project-level, so not

2022-06-02 14:11 UTC, martinmladenov approved these changes

2022-06-02 14:50 UTC, kirilvasilev16 approved these changes
LGTM!

2022-06-02 14:51 UTC, merged