Create LICENSE.mp
ciselab/TestGenie pull request #214
Opened 2022-10-14 14:48 UTC by apanichella

# Description of changes made
*Please describe what changes have you made in this merge request*

# Why is merge request needed
*Please write why your merge request is needed*

# Other notes
Closes #*issue_number*

*Please write if you have anything to add*

# What is missing?
*Please mention if anything is missing for this merge request, e.g you have decided to move something to the next merge request*

- [ ] I have checked that I am merging into correct branch

2022-10-14 15:23 UTC, pderakhshanfar approved these changes

2022-10-14 15:26 UTC, mitchellolsthoorn requested changes
The file extension was probably meant to be MD not MP. Although, license files by default don't have any extension. So, I would recommend to either remove the extension or change it to the markdown extension.

2022-10-14 19:09 UTC, mitchellolsthoorn approved these changes

2022-10-16 08:38 UTC, pderakhshanfar approved these changes

2022-10-16 08:39 UTC, merged