40 clickable test names
ciselab/TestGenie pull request #53
Opened 2022-05-10 16:21 UTC by bolkhod

# Description of changes made
When you click on the green elements in the gutter (visualisation), a new popup menu appears. Test names which cover a line are now clickable. Clicking these test names makes the corresponding mini-editor in the toolwindow have a custom color (the same shade of green, for now). After 10 seconds, the color resets. This way a test code is highlighted for a short moment and can easily be spotted.

# Why is merge request needed
Because the client suggested this feature. This feature generally helps finding tests that cover a specific line (in the toolwindow).

# Other notes
The UI of the popup menu has gotten uglier after the change.

# What is missing?
Custom colors can be added in the future - future option in settings
Better UI design for the popup menu

- [x] I have checked that I am merging into correct branch

2022-05-10 18:10 UTC, martinmladenov commented
Is this PR ready for review?

2022-05-10 18:37 UTC, bolkhod commented
> Is this PR ready for review?

The core of the code is. I am just aware that some other PRs (which will likely be merged prior to this one) will have conflicts.
I aim to merge dev into the branch and solve them, before fully opening.
But you can check the added stuff already, its shouldn't change (much)

2022-05-11 00:16 UTC, jzelenjak approved these changes
The colouring of the selected test looks very cool in my opinion.  Especially, implementing the reset in a thread was a very clever approach.
Good job!

2022-05-11 00:16 UTC, jzelenjak commented on src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/listener/TestGenerationResultListenerImpl.kt
> +            testCaseDisplayService.displayTestCases(testReport)
This is much better to read!

2022-05-11 00:16 UTC, jzelenjak commented on src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
> +                Thread {
I like this way of doing it. Well done!

2022-05-11 08:14 UTC, bolkhod commented on src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
> +                Thread {
thanks

2022-05-12 15:14 UTC, jzelenjak requested changes
After running your code, i noticed that there is an issue that it is not possible to highlight the test when running the generation more than once. This has to be addressed.

Otherwise, everything looks good to me

2022-05-12 15:43 UTC, jzelenjak submitted a review, later dismissed
Thank you for fixing the bug!

2022-05-12 16:27 UTC, bolkhod commented on src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
> +                editor.background = Color(100, 150, 20, 30)
great idea! I have done exactly that

2022-05-12 16:28 UTC, bolkhod commented on src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/coverage/CoverageRenderer.kt
> +        for (i in tests) {
yes, this is now `testNames` to make it clear to other devs

2022-05-12 16:38 UTC, kirilvasilev16 approved these changes
Thank you for incorporating my feedback!

2022-05-12 16:39 UTC, jzelenjak approved these changes

2022-05-12 16:40 UTC, merged