Option to provide a custom java binary path
ciselab/TestGenie pull request #85
Opened 2022-05-19 14:14 UTC by martinmladenov

# Description of changes made
Added a settings option to provide a custom Java binary instead of simply using the default `java` command.

# Why is merge request needed
The default `java` command may not be compatible with EvoSuite (e.g. if it is a too old or new version).

# Other notes
Closes #63

2022-05-19 15:58 UTC, jzelenjak submitted a review, later dismissed
Good job, Marti!
I have tested it and it works on my machine.
The feature will definitely be useful for our plugini

2022-05-19 15:58 UTC, jzelenjak commented on src/main/resources/defaults/TestGenie.properties
> +stoppingCondition = MAXTIME
Why do they have spaces near the = sign?

2022-05-20 09:04 UTC, kirilvasilev16 requested changes
When a I provide an incorrect java path, I get an exception. Can you change this to have a MessageBox appear that notifies the user that an EvoSuite exception occured?

2022-05-20 10:39 UTC, martinmladenov commented
> When a I provide an incorrect java path, I get an exception. Can you change this to have a MessageBox appear that notifies the user that an EvoSuite exception occured?

Thank you for the comment - I made it show notifications instead.

2022-05-20 10:52 UTC, kirilvasilev16 approved these changes
I like the notification even more than what I suggested. Good job! It works normally on Windows ;)

2022-05-20 11:24 UTC, lyuben-todorov approved these changes
LGTM!

2022-05-20 11:24 UTC, merged